# Generated by Django 4.2.5 on 2023-12-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_exam_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="Exercises", to="main.bookquestion"
            ),
        ),
    ]
